### ISSUE TITLE
Won't compile on modern glibc

### ISSUE THREAD

**Issue by TheCranston** [mlangelaar/jnos2#3]
The password management code relies on single DES glibc function calls which have been pulled from the library due to age and insecurity.  The code will now not compile complaining about 

`
/usr/bin/ld: net.a(j2pwrtns.o): in function j2setkey:
/home/pi/src/jnos2/j2pwmgr/j2pwrtns.c:69: undefined reference to setkey
/usr/bin/ld: net.a(j2pwrtns.o): in function j2userpasswd:
/home/pi/src/jnos2/j2pwmgr/j2pwrtns.c:186: undefined reference to encrypt
collect2: error: ld returned 1 exit status
make: *** [makefile:156: jnos] Error 1
`

Please help with either a work around or how to make it work with the "compatibility" library of libxcrypt.  Thanks!

**Comment by mlangelaar** [comment]
Good day,

Thanks for the update, interesting, and thanks for your concern
about the age old DES stuff. Well aware of how ancient it is :)

That entire code base needs to be pulled and updated to my
official release. Unfortunately it was a half baked version, but
in case I get hit by a bus, I wanted it on a public repository.

Perhaps I need to remove it permanently, the JNOS on my github
is there strictly as a backup or alternative download, nothing more.

I don't do commits to it, that gets done on my 'official' system
elsewhere, so having said that perhaps it's time to delete it.

Maiko

**Comment by TheCranston** [comment]
Maiko,
Thanks for the follow up.  I actually pulled the code via rsync, the official way.  I just didn’t see a place to give feedback, so I used github for that.
Anyway, is there a way I can get around the issue?

-Ben

**Comment by mlangelaar** [comment]
Hi Ben,

I guess I need to get up to the 'latest' glib, I do that from time
to time, that's what happens when you get stuck on a 'stable'
release for too long :]

Any of that DES code and j2pwmgr stuff was meant strictly
for the winlink support. If your compile actually got to that
point, then you can just ignore the error. The jnos binary
should already be there for you. If not, let me know.

I'll get the latest glib put onto a VM here and fix all the latest
errors and warnings. The challenge with this is the makefile
needs to be dynamic, I actually have a makefile in the works,
but just haven't had time to make it 'official' yet. Makefiles are
not my strength.

Thanks for posting, perhaps leaving it on github is not a bad
idea, I just need to get the darn repository updated.

Maiko

**Comment by TheCranston** [comment]
Maiko,
Well, it won’t link the code at the end because of the missing library functions, so no jnos binary is generated.  Can I at compile time dump the winlink stuff?  I’m going to be talking with an instance of direwolf in my application.

-Ben

**Comment by mlangelaar** [comment]
Did you check for the binary, the j2pwmgr is AFTER the jnos is compiled,
that's why I mentioned it.

PS : can we do this direct (offline), I noticed this is all getting 
posted to github.

Maiko

**Comment by TheCranston** [comment]
Sure thing.  Let's work the issue directly.  Thanks!
I did check for the generation of a jnos exec and it is not there.  

find . -name jnos -print

returned nothing.  I'll forward the build log once we are direct.  thanks

**Comment by mlangelaar** [comment]
Complete revamp of the JNOS password management, openssl libs
for anything that requires hashing and encryption, trying to catch up
with modern day practices, if I don't have to encrypt, I won't.
